name: main Deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          host: ec2-34-238-254-200.compute-1.amazonaws.com
          port: 22
          script: |
            sudo chown -R ubuntu:ubuntu /home/ubuntu/simple-nodejs-app/.git
            sudo chmod -R u+rw /home/ubuntu/simple-nodejs-app/.git
            cd /home/ubuntu/simple-nodejs-app/
            git config --global --add safe.directory /home/ubuntu/simple-nodejs-app
            git checkout master
            git fetch origin master
            git reset --hard origin/master
