name: development Deployment

on:
  push:
    branches: [ development ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          host: ec2-34-238-254-200.compute-1.amazonaws.com
          port: 22
          script: |
            cd /home/ubuntu/simple-nodejs-app/
            # Build the Docker image with a tag
            sudo docker build -t ghj .
            # If needed, run the container after build
            # sudo docker run -d --name my-app -p 80:80 ghj
