name: Stage Deployment

on:
  push:
    branches: [ development ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          host: ec2-34-238-254-200.compute-1.amazonaws.com
          port: 22
          script: |
            cd /home/ubuntu/simple-nodejs-app/
            # Pull the latest code and rebuild with Docker Compose
            sudo docker-compose down
            sudo docker-compose up --build -d
