name: Production Deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: appleboy/ssh-action@master
        
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        with:
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          host: ec2-34-238-254-200.compute-1.amazonaws.com
          port: 22
          script: |
            cd /home/sabari-tech/Sabari/Projects/sabari7868
            sudo docker build -t ghj .

